//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DunBrad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DunBEntities : DbContext
    {
        public DunBEntities()
            : base("name=DunBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENT> AGENTS { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
    
        public virtual ObjectResult<GetSumAgentCodeByYear_Result> GetSumAgentCodeByYear(Nullable<int> oRD_DATE)
        {
            var oRD_DATEParameter = oRD_DATE.HasValue ?
                new ObjectParameter("ORD_DATE", oRD_DATE) :
                new ObjectParameter("ORD_DATE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSumAgentCodeByYear_Result>("GetSumAgentCodeByYear", oRD_DATEParameter);
        }
    
        public virtual ObjectResult<GetAgentCodeByRowNumber_Result> GetAgentCodeByRowNumber(Nullable<int> top_Rows_Count, string aGENT_CODE_list, Nullable<int> rownumentered)
        {
            var top_Rows_CountParameter = top_Rows_Count.HasValue ?
                new ObjectParameter("Top_Rows_Count", top_Rows_Count) :
                new ObjectParameter("Top_Rows_Count", typeof(int));
    
            var aGENT_CODE_listParameter = aGENT_CODE_list != null ?
                new ObjectParameter("AGENT_CODE_list", aGENT_CODE_list) :
                new ObjectParameter("AGENT_CODE_list", typeof(string));
    
            var rownumenteredParameter = rownumentered.HasValue ?
                new ObjectParameter("Rownumentered", rownumentered) :
                new ObjectParameter("Rownumentered", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgentCodeByRowNumber_Result>("GetAgentCodeByRowNumber", top_Rows_CountParameter, aGENT_CODE_listParameter, rownumenteredParameter);
        }
    
        public virtual ObjectResult<GetAgentsByQtyOrders_Result> GetAgentsByQtyOrders(Nullable<int> numentered, Nullable<int> yearentered)
        {
            var numenteredParameter = numentered.HasValue ?
                new ObjectParameter("Numentered", numentered) :
                new ObjectParameter("Numentered", typeof(int));
    
            var yearenteredParameter = yearentered.HasValue ?
                new ObjectParameter("Yearentered", yearentered) :
                new ObjectParameter("Yearentered", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgentsByQtyOrders_Result>("GetAgentsByQtyOrders", numenteredParameter, yearenteredParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetRowsCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetRowsCount");
        }
    
        public virtual ObjectResult<Nullable<int>> GetRowsCount1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetRowsCount1");
        }
    }
}
